<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\ProductImage;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'name' => 'Xe Tải Điện PD-T2000',
                'description' => 'Xe tải điện đa năng tải trọng 2 tấn, thiết kế dành riêng cho vận chuyển hàng hóa trong khu công nghiệp, nhà máy, kho bãi. Động cơ AC 5kW mạnh mẽ, pin lithium-ion 72V/150Ah cho phạm vi hoạt động lên đến 80km mỗi lần sạc.',
                'price' => 185000000,
                'sku' => 'PD-T2000',
                'stock' => 15,
                'specifications' => [
                    'Tải trọng' => '2.000 kg',
                    'Động cơ' => 'AC 5kW',
                    'Pin' => 'Lithium-ion 72V/150Ah',
                    'Phạm vi' => '80 km/lần sạc',
                    'Tốc độ tối đa' => '30 km/h',
                    'Thời gian sạc' => '6-8 giờ',
                    'Kích thước (DxRxC)' => '4200 x 1500 x 2100 mm',
                    'Trọng lượng không tải' => '1.200 kg',
                    'Phanh' => 'Đĩa thủy lực 4 bánh',
                    'Lốp' => '195/65R15',
                ],
                'status' => 'active',
            ],
            [
                'name' => 'Xe Tải Điện PD-T3000',
                'description' => 'Xe tải điện tải trọng 3 tấn dành cho công việc nặng. Khung gầm thép cường lực, hệ thống treo kép, phù hợp vận chuyển hàng hóa lớn trong khu công nghiệp quy mô lớn và cảng biển.',
                'price' => 265000000,
                'sku' => 'PD-T3000',
                'stock' => 8,
                'specifications' => [
                    'Tải trọng' => '3.000 kg',
                    'Động cơ' => 'AC 7.5kW',
                    'Pin' => 'Lithium-ion 96V/200Ah',
                    'Phạm vi' => '60 km/lần sạc',
                    'Tốc độ tối đa' => '25 km/h',
                    'Thời gian sạc' => '8-10 giờ',
                    'Kích thước (DxRxC)' => '5100 x 1700 x 2200 mm',
                    'Trọng lượng không tải' => '1.800 kg',
                    'Phanh' => 'Đĩa thủy lực + phanh tái sinh',
                    'Lốp' => '215/70R16',
                ],
                'status' => 'active',
            ],
            [
                'name' => 'Xe Điện Du Lịch PD-P14',
                'description' => 'Xe điện chở khách 14 chỗ cao cấp, thiết kế sang trọng dành cho resort, khu du lịch, sân golf. Ghế da simili cao cấp, mái che rộng, hệ thống treo độc lập cho trải nghiệm êm ái.',
                'price' => 320000000,
                'sku' => 'PD-P14',
                'stock' => 5,
                'specifications' => [
                    'Số chỗ ngồi' => '14 chỗ (gồm tài xế)',
                    'Động cơ' => 'AC 7.5kW',
                    'Pin' => 'Lithium-ion 72V/150Ah',
                    'Phạm vi' => '100 km/lần sạc',
                    'Tốc độ tối đa' => '28 km/h',
                    'Thời gian sạc' => '6-8 giờ',
                    'Kích thước (DxRxC)' => '5800 x 1550 x 2100 mm',
                    'Trọng lượng không tải' => '1.100 kg',
                    'Ghế' => 'Da simili cao cấp chống thấm',
                    'Mái che' => 'Composite chống UV',
                ],
                'status' => 'active',
            ],
            [
                'name' => 'Xe Điện Chở Khách PD-P8',
                'description' => 'Xe điện 8 chỗ gọn nhẹ, linh hoạt, phù hợp cho bệnh viện, trường học, khu đô thị. Thiết kế thân thiện, dễ vận hành, chi phí bảo trì thấp.',
                'price' => 195000000,
                'sku' => 'PD-P8',
                'stock' => 12,
                'specifications' => [
                    'Số chỗ ngồi' => '8 chỗ (gồm tài xế)',
                    'Động cơ' => 'AC 4kW',
                    'Pin' => 'Lithium-ion 48V/150Ah',
                    'Phạm vi' => '90 km/lần sạc',
                    'Tốc độ tối đa' => '25 km/h',
                    'Thời gian sạc' => '5-7 giờ',
                    'Kích thước (DxRxC)' => '3800 x 1450 x 1950 mm',
                    'Trọng lượng không tải' => '750 kg',
                    'Bán kính quay vòng' => '4.5 m',
                    'Hệ thống treo' => 'Lò xo lá phía trước, nhíp phía sau',
                ],
                'status' => 'active',
            ],
            [
                'name' => 'Xe Golf Điện PD-G4',
                'description' => 'Xe golf điện 4 chỗ đẳng cấp quốc tế, thiết kế tinh tế dành cho sân golf, biệt thự, resort cao cấp. Chạy êm, bền bỉ, phong cách.',
                'price' => 145000000,
                'sku' => 'PD-G4',
                'stock' => 20,
                'specifications' => [
                    'Số chỗ ngồi' => '4 chỗ',
                    'Động cơ' => 'AC 3kW',
                    'Pin' => 'Lithium-ion 48V/100Ah',
                    'Phạm vi' => '80 km/lần sạc',
                    'Tốc độ tối đa' => '24 km/h',
                    'Thời gian sạc' => '4-6 giờ',
                    'Kích thước (DxRxC)' => '2880 x 1200 x 1900 mm',
                    'Trọng lượng không tải' => '450 kg',
                    'Khoang hành lý' => 'Giỏ xách golf phía sau',
                    'Tùy chọn' => 'Kính chắn gió, đèn LED, hệ thống GPS',
                ],
                'status' => 'active',
            ],
            [
                'name' => 'Xe Điện Chở Khách PD-P4',
                'description' => 'Xe điện mini 4 chỗ ngồi, kích thước nhỏ gọn, phù hợp tuần tra, vận chuyển trong không gian hẹp như bệnh viện, tòa nhà văn phòng, khu dân cư.',
                'price' => 89000000,
                'sku' => 'PD-P4',
                'stock' => 25,
                'specifications' => [
                    'Số chỗ ngồi' => '4 chỗ',
                    'Động cơ' => 'AC 3kW',
                    'Pin' => 'Lithium-ion 48V/100Ah',
                    'Phạm vi' => '80 km/lần sạc',
                    'Tốc độ tối đa' => '25 km/h',
                    'Thời gian sạc' => '4-6 giờ',
                    'Kích thước (DxRxC)' => '2750 x 1350 x 1900 mm',
                    'Trọng lượng không tải' => '420 kg',
                    'Bán kính quay vòng' => '3.5 m',
                    'Phanh' => 'Đĩa thủy lực 4 bánh',
                ],
                'status' => 'active',
            ],
            [
                'name' => 'Xe Nâng Điện PD-F15',
                'description' => 'Xe nâng điện counterbalance tải trọng 1.5 tấn, chiều cao nâng 3m. Phù hợp cho kho bãi, nhà xưởng, trung tâm logistics cần di chuyển pallet và hàng hóa nặng.',
                'price' => 355000000,
                'sku' => 'PD-F15',
                'stock' => 6,
                'specifications' => [
                    'Tải trọng nâng' => '1.500 kg',
                    'Chiều cao nâng tối đa' => '3.000 mm',
                    'Động cơ di chuyển' => 'AC 4.5kW',
                    'Động cơ nâng' => 'DC 11kW',
                    'Pin' => 'Lead-acid 48V/400Ah',
                    'Tốc độ di chuyển' => '12 km/h',
                    'Chiều dài fork' => '1070 mm',
                    'Bán kính quay vòng' => '2.1 m',
                    'Trọng lượng' => '3.200 kg',
                    'Thời gian sạc' => '8-10 giờ',
                ],
                'status' => 'active',
            ],
            [
                'name' => 'Xe Kéo Điện PD-TW5',
                'description' => 'Xe kéo điện (tow tractor) sức kéo 5 tấn, chuyên dùng kéo moóc hàng hóa trong nhà máy, sân bay, kho bãi lớn. Thiết kế compact, cơ động cao.',
                'price' => 225000000,
                'sku' => 'PD-TW5',
                'stock' => 10,
                'specifications' => [
                    'Sức kéo' => '5.000 kg',
                    'Động cơ' => 'AC 7kW',
                    'Pin' => 'Lithium-ion 80V/200Ah',
                    'Phạm vi' => '70 km/lần sạc',
                    'Tốc độ tối đa' => '20 km/h',
                    'Thời gian sạc' => '5-7 giờ',
                    'Kích thước (DxRxC)' => '2400 x 1100 x 1450 mm',
                    'Trọng lượng' => '1.500 kg',
                    'Móc kéo' => 'Tự động khóa/mở',
                    'Phanh' => 'Đĩa thủy lực + phanh tái sinh',
                ],
                'status' => 'active',
            ],
            [
                'name' => 'Xe Điện Tuần Tra PD-S2',
                'description' => 'Xe điện tuần tra 2 chỗ ngồi chuyên dụng cho bảo vệ, an ninh. Trang bị đèn cảnh báo, còi hú, hộp đựng dụng cụ phía sau. Nhỏ gọn, cơ động, tiết kiệm.',
                'price' => 78000000,
                'sku' => 'PD-S2',
                'stock' => 18,
                'specifications' => [
                    'Số chỗ ngồi' => '2 chỗ',
                    'Động cơ' => 'AC 3kW',
                    'Pin' => 'Lithium-ion 48V/80Ah',
                    'Phạm vi' => '100 km/lần sạc',
                    'Tốc độ tối đa' => '30 km/h',
                    'Thời gian sạc' => '4-5 giờ',
                    'Kích thước (DxRxC)' => '2600 x 1250 x 1850 mm',
                    'Trọng lượng không tải' => '380 kg',
                    'Trang bị' => 'Đèn cảnh báo LED, còi, hộp công cụ',
                    'Phanh' => 'Đĩa thủy lực',
                ],
                'status' => 'active',
            ],
            [
                'name' => 'Xe Điện Chở Rác PD-GC1000',
                'description' => 'Xe điện chuyên dụng thu gom rác tải trọng 1 tấn, thiết kế thùng rác tự đổ thủy lực. Lý tưởng cho khu đô thị, khu công nghiệp, resort, trường học.',
                'price' => 135000000,
                'sku' => 'PD-GC1000',
                'stock' => 7,
                'specifications' => [
                    'Tải trọng' => '1.000 kg',
                    'Dung tích thùng' => '1.5 m³',
                    'Động cơ' => 'AC 4kW',
                    'Pin' => 'Lithium-ion 60V/120Ah',
                    'Phạm vi' => '70 km/lần sạc',
                    'Tốc độ tối đa' => '22 km/h',
                    'Thời gian sạc' => '5-7 giờ',
                    'Hệ thống đổ' => 'Thủy lực tự động',
                    'Kích thước (DxRxC)' => '3600 x 1400 x 2000 mm',
                    'Trọng lượng không tải' => '950 kg',
                ],
                'status' => 'active',
            ],
        ];

        foreach ($products as $data) {
            Product::create([
                'name' => $data['name'],
                'slug' => Str::slug($data['name']),
                'description' => $data['description'],
                'price' => $data['price'],
                'sku' => $data['sku'],
                'stock' => $data['stock'],
                'specifications' => $data['specifications'],
                'status' => $data['status'],
            ]);
        }
    }
}
