<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title inertia>{{ config('app.name', 'Laravel') }}</title>

        @if(filled($rootSite['favicon_url'] ?? null))
            <link rel="icon" href="{{ $rootSite['favicon_url'] }}">
            <link rel="shortcut icon" href="{{ $rootSite['favicon_url'] }}">
        @endif

        @php($theme = $rootSite['theme'])

        {{-- Canonical initial theme: values and variable names are generated by ThemeTokenService. --}}
        <style id="storefront-theme">
            :root {
                @foreach($theme['css_variables'] as $variable => $value)
                    {!! $variable !!}: {!! $value !!};
                @endforeach
            }
        </style>

        <!-- Validated initial fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link id="storefront-theme-fonts" href="{{ $theme['font_stylesheet_url'] }}" rel="stylesheet">

        <!-- Scripts -->
        @routes
        @vite(['resources/js/app.js', "resources/js/Pages/{$page['component']}.vue"])
        @inertiaHead
    </head>
    <body class="font-sans antialiased">
        @inertia
    </body>
</html>
