<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import AdminConfirmDialog from '@/Components/Admin/AdminConfirmDialog.vue';
import AdminDataCard from '@/Components/Admin/AdminDataCard.vue';
import AdminErrorSummary from '@/Components/Admin/AdminErrorSummary.vue';
import AdminFormField from '@/Components/Admin/AdminFormField.vue';
import AdminMediaPicker from '@/Components/Admin/AdminMediaPicker.vue';
import AdminPageHeader from '@/Components/Admin/AdminPageHeader.vue';
import AdminSelect from '@/Components/Admin/AdminSelect.vue';
import AdminTextInput from '@/Components/Admin/AdminTextInput.vue';
import AdminTextarea from '@/Components/Admin/AdminTextarea.vue';
import { Head, Link, router, useForm } from '@inertiajs/vue3';
import draggable from 'vuedraggable';
import { ref } from 'vue';

const props = defineProps({ page: { type: Object, required: true } }); const module = props.page.module; const product = module.product;
const form = useForm({ name: product?.name || '', slug: product?.slug || '', sku: product?.sku || '', description: product?.description || '', price: product?.price ?? 0, stock: product?.stock ?? 0, status: product?.status || 'active', specifications: product?.specifications?.length ? product.specifications : [{ key: '', value: '' }], version: product?.version || null });
const showPicker = ref(false); const pickerIs360 = ref(false); const deletingImage = ref(null); const uploading = ref(false); const normalImages = ref((product?.images || []).filter((image) => !image.is_360)); const images360 = ref((product?.images || []).filter((image) => image.is_360));
const addSpec = () => form.specifications.push({ key: '', value: '' }); const removeSpec = (index) => form.specifications.splice(index, 1); const save = () => product ? form.put(route('admin.products.update', product.id), { onSuccess: (page) => { if (page.props.page?.module?.product?.version) form.version = page.props.page.module.product.version; form.defaults(form.data()); form.reset(); } }) : form.post(route('admin.products.store'));
const uploadImages = (event, is360) => { if (!product || !event.target.files.length) return; const data = new FormData(); Array.from(event.target.files).forEach((file) => data.append('images[]', file)); if (is360) data.append('is_360', '1'); uploading.value = true; router.post(route('admin.products.images.upload', product.id), data, { forceFormData: true, preserveScroll: true, onFinish: () => { uploading.value = false; } }); };
const selectMedia = (media) => { showPicker.value = false; if (product) router.post(route('admin.products.images.from-media', product.id), { media_id: media.id, is_360: pickerIs360.value ? 1 : 0 }, { preserveScroll: true }); };
const deleteImage = () => { router.delete(route('admin.products.images.delete', [product.id, deletingImage.value.id]), { preserveScroll: true, onFinish: () => { deletingImage.value = null; } }); };
const saveOrder = () => { const order = [...normalImages.value, ...images360.value].map((image) => image.id); router.post(route('admin.products.images.reorder', product.id), { order }, { preserveScroll: true }); };
</script>

<template>
    <Head :title="page.meta.title" /><AuthenticatedLayout><AdminPageHeader :title="page.meta.title"><Link :href="route('admin.products.index')" class="text-sm text-admin-content-muted">Back</Link></AdminPageHeader><div class="mt-6 space-y-6"><AdminErrorSummary :errors="form.errors" /><AdminDataCard title="Product details"><form class="space-y-5" @submit.prevent="save"><div class="grid gap-4 md:grid-cols-2"><AdminFormField label="Name" for-id="product-name" :error="form.errors.name"><AdminTextInput id="product-name" v-model="form.name" /></AdminFormField><AdminFormField label="Slug" for-id="product-slug" :error="form.errors.slug"><AdminTextInput id="product-slug" v-model="form.slug" /></AdminFormField><AdminFormField label="SKU" for-id="product-sku" :error="form.errors.sku"><AdminTextInput id="product-sku" v-model="form.sku" /></AdminFormField><AdminFormField label="Price" for-id="product-price" :error="form.errors.price"><AdminTextInput id="product-price" v-model.number="form.price" type="number" /></AdminFormField><AdminFormField label="Stock" for-id="product-stock" :error="form.errors.stock"><AdminTextInput id="product-stock" v-model.number="form.stock" type="number" /></AdminFormField><AdminFormField label="Status" for-id="product-status" :error="form.errors.status"><AdminSelect id="product-status" v-model="form.status" :options="module.statuses" /></AdminFormField></div><AdminFormField label="Description" for-id="product-description" :error="form.errors.description"><AdminTextarea id="product-description" v-model="form.description" rows="8" /></AdminFormField><AdminFormField label="Specifications" :error="form.errors.specifications"><div class="space-y-2"><div v-for="(spec, index) in form.specifications" :key="index" class="flex gap-2"><AdminTextInput v-model="spec.key" placeholder="Name" /><AdminTextInput v-model="spec.value" placeholder="Value" /><button type="button" class="px-2 text-admin-danger" :aria-label="`Remove specification ${index + 1}`" @click="removeSpec(index)">×</button></div><button type="button" class="text-sm text-admin-accent" @click="addSpec">Add specification</button></div></AdminFormField><div class="flex justify-end"><button type="submit" :disabled="form.processing" class="rounded bg-admin-accent px-5 py-2 text-sm font-semibold text-admin-page">{{ form.processing ? 'Saving...' : 'Save product' }}</button></div></form></AdminDataCard>
        <AdminDataCard v-if="product" title="Product images"><div class="flex flex-wrap gap-3"><label class="cursor-pointer rounded border border-admin-border px-4 py-2 text-sm text-admin-content"><input type="file" class="sr-only" multiple accept="image/jpeg,image/png,image/webp,image/gif" :disabled="uploading" @change="uploadImages($event, false)" />Upload normal images</label><label class="cursor-pointer rounded border border-admin-border px-4 py-2 text-sm text-admin-content"><input type="file" class="sr-only" multiple accept="image/jpeg,image/png,image/webp,image/gif" :disabled="uploading" @change="uploadImages($event, true)" />Upload 360 images</label><button type="button" class="rounded border border-admin-border px-4 py-2 text-sm text-admin-content" @click="pickerIs360 = false; showPicker = true">Attach normal media</button><button type="button" class="rounded border border-admin-border px-4 py-2 text-sm text-admin-content" @click="pickerIs360 = true; showPicker = true">Attach 360 media</button></div><section class="mt-5"><h3 class="text-sm font-semibold text-admin-content">Normal</h3><draggable v-model="normalImages" item-key="id" class="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-5" handle=".image-handle" @end="saveOrder"><template #item="{ element: image }"><div class="relative border border-admin-border p-2"><button type="button" class="image-handle absolute left-1 top-1 cursor-grab text-xs text-admin-content-muted" aria-label="Drag image">::</button><img :src="image.url" :alt="image.file_name" class="aspect-square w-full object-cover" /><button type="button" class="absolute right-1 top-1 bg-admin-danger px-2 py-1 text-xs text-white" @click="deletingImage = image">Delete</button></div></template></draggable></section><section class="mt-6"><h3 class="text-sm font-semibold text-admin-content">360</h3><draggable v-model="images360" item-key="id" class="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-5" handle=".image-handle" @end="saveOrder"><template #item="{ element: image }"><div class="relative border border-admin-border p-2"><button type="button" class="image-handle absolute left-1 top-1 cursor-grab text-xs text-admin-content-muted" aria-label="Drag image">::</button><img :src="image.url" :alt="image.file_name" class="aspect-square w-full object-cover" /><button type="button" class="absolute right-1 top-1 bg-admin-danger px-2 py-1 text-xs text-white" @click="deletingImage = image">Delete</button></div></template></draggable></section></AdminDataCard></div><AdminMediaPicker :open="showPicker" @close="showPicker = false" @select="selectMedia" /><AdminConfirmDialog :open="!!deletingImage" title="Delete product image" message="Only the product-owned copy is deleted; the original media remains." confirm-label="Delete image" danger @cancel="deletingImage = null" @confirm="deleteImage" /></AuthenticatedLayout>
</template>
