<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import AdminConfirmDialog from '@/Components/Admin/AdminConfirmDialog.vue';
import AdminDataCard from '@/Components/Admin/AdminDataCard.vue';
import AdminPageHeader from '@/Components/Admin/AdminPageHeader.vue';
import { Head, Link, router } from '@inertiajs/vue3';
import { ref } from 'vue';
const props = defineProps({ page: { type: Object, required: true } }); const deleting = ref(null); const destroy = () => router.delete(deleting.value.delete_url, { onFinish: () => { deleting.value = null; } });
</script>

<template><Head :title="page.meta.title" /><AuthenticatedLayout><AdminPageHeader :title="page.meta.title"><Link :href="route('admin.post-categories.create')" class="rounded-lg bg-admin-accent px-4 py-2 text-sm font-semibold text-admin-page">Thêm danh mục</Link></AdminPageHeader><AdminDataCard title="Cây danh mục" class="mt-6"><ul class="space-y-2"><template v-for="category in page.module.items" :key="category.id"><li class="border border-admin-border p-3"><div class="flex items-center justify-between gap-3"><div><Link :href="category.edit_url" class="font-medium text-admin-content hover:text-admin-accent">{{ category.name }}</Link><p class="text-xs text-admin-content-muted">{{ category.posts_count }} bài viết · {{ category.children_count }} danh mục con</p></div><div><Link :href="category.edit_url" class="mr-3 text-sm text-admin-accent">Sửa</Link><button v-if="!category.children_count && !category.posts_count" type="button" class="text-sm text-admin-danger" @click="deleting = category">Xóa</button></div></div><ul v-if="category.children?.length" class="mt-3 space-y-2 border-l border-admin-border pl-4"><li v-for="child in category.children" :key="child.id" class="flex items-center justify-between border-b border-admin-border py-2 text-sm"><Link :href="child.edit_url" class="text-admin-content hover:text-admin-accent">{{ child.name }}</Link><span class="text-xs text-admin-content-muted">{{ child.posts_count }} bài viết</span></li></ul></li></template></ul><p v-if="!page.module.items.length" class="py-10 text-center text-sm text-admin-content-muted">Chưa có danh mục.</p></AdminDataCard><AdminConfirmDialog :open="!!deleting" title="Xóa danh mục" message="Danh mục có bài viết hoặc danh mục con sẽ không thể xóa." confirm-label="Xóa danh mục" danger @cancel="deleting = null" @confirm="destroy" /></AuthenticatedLayout></template>
