<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import AdminDataCard from '@/Components/Admin/AdminDataCard.vue';
import AdminErrorSummary from '@/Components/Admin/AdminErrorSummary.vue';
import AdminFormField from '@/Components/Admin/AdminFormField.vue';
import AdminMediaPicker from '@/Components/Admin/AdminMediaPicker.vue';
import AdminPageHeader from '@/Components/Admin/AdminPageHeader.vue';
import AdminSelect from '@/Components/Admin/AdminSelect.vue';
import AdminTextInput from '@/Components/Admin/AdminTextInput.vue';
import AdminTextarea from '@/Components/Admin/AdminTextarea.vue';
import { Head, Link, useForm } from '@inertiajs/vue3';
import { ref } from 'vue';
const props = defineProps({ page: { type: Object, required: true } }); const module = props.page.module; const post = module.post; const picker = ref(false);
const form = useForm({ title: post?.title || '', slug: post?.slug || '', post_category_id: post?.post_category_id || '', summary: post?.summary || '', content: post?.content || '', status: post?.status || 'draft', featured_media_id: post?.featured_media_id || null, version: post?.version || null });
const save = () => post ? form.put(route('admin.posts.update', post.id)) : form.post(route('admin.posts.store')); const selectMedia = (media) => { form.featured_media_id = media.id; picker.value = false; };
</script>

<template><Head :title="page.meta.title" /><AuthenticatedLayout><AdminPageHeader :title="page.meta.title"><Link :href="route('admin.posts.index')" class="text-sm text-admin-content-muted hover:text-admin-content">Quay lại</Link></AdminPageHeader><div class="mt-6 space-y-6"><AdminErrorSummary :errors="form.errors" /><AdminDataCard title="Thông tin bài viết"><form class="space-y-5" @submit.prevent="save"><div class="grid gap-4 md:grid-cols-2"><AdminFormField label="Tiêu đề" for-id="post-title" :error="form.errors.title"><AdminTextInput id="post-title" v-model="form.title" /></AdminFormField><AdminFormField label="Slug" for-id="post-slug" :error="form.errors.slug"><AdminTextInput id="post-slug" v-model="form.slug" /></AdminFormField><AdminFormField label="Danh mục" for-id="post-category" :error="form.errors.post_category_id"><AdminSelect id="post-category" v-model="form.post_category_id" :options="[{ key: '', label: 'Chưa phân loại' }, ...module.categories.map(category => ({ key: category.id, label: category.name }))]" /></AdminFormField><AdminFormField label="Trạng thái" for-id="post-status" :error="form.errors.status"><AdminSelect id="post-status" v-model="form.status" :options="module.statuses" /></AdminFormField></div><AdminFormField label="Tóm tắt" for-id="post-summary" :error="form.errors.summary"><AdminTextarea id="post-summary" v-model="form.summary" rows="4" /></AdminFormField><AdminFormField label="Nội dung" for-id="post-content" :error="form.errors.content"><AdminTextarea id="post-content" v-model="form.content" rows="14" hint="Nội dung được lưu theo Rich HTML contract hiện có." /></AdminFormField><AdminFormField label="Ảnh đại diện" :error="form.errors.featured_media_id"><div class="flex items-center gap-3"><img v-if="post?.featured_image_url" :src="post.featured_image_url" alt="" class="h-16 w-24 object-cover" /><button type="button" class="rounded-lg border border-admin-border px-4 py-2 text-sm text-admin-content" @click="picker = true">Chọn từ Media</button><span v-if="form.featured_media_id" class="text-sm text-admin-content-muted">Đã chọn Media #{{ form.featured_media_id }}</span></div></AdminFormField><div class="flex justify-end"><button type="submit" :disabled="form.processing" class="rounded-lg bg-admin-accent px-5 py-2 text-sm font-semibold text-admin-page disabled:opacity-50">{{ form.processing ? 'Đang lưu...' : 'Lưu bài viết' }}</button></div></form></AdminDataCard></div><AdminMediaPicker :open="picker" :items="module.media" @close="picker = false" @select="selectMedia" /></AuthenticatedLayout></template>
