<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import AdminDataCard from '@/Components/Admin/AdminDataCard.vue';
import AdminErrorSummary from '@/Components/Admin/AdminErrorSummary.vue';
import AdminFormField from '@/Components/Admin/AdminFormField.vue';
import AdminPageHeader from '@/Components/Admin/AdminPageHeader.vue';
import AdminSelect from '@/Components/Admin/AdminSelect.vue';
import AdminTextInput from '@/Components/Admin/AdminTextInput.vue';
import { Head, Link, router, useForm } from '@inertiajs/vue3';
import { ref } from 'vue';
const props = defineProps({ page: { type: Object, required: true } }); const module = props.page.module; const menu = module.menu; const form = useForm({ name: menu?.name || '', location: menu?.location || 'header' }); const items = ref(menu?.items || []); const itemForm = useForm({ items: items.value, version: menu?.version || null });
const save = () => menu ? form.put(route('admin.menus.update', menu.id)) : form.post(route('admin.menus.store')); const addItem = () => items.value.push({ client_key: `new-${Date.now()}`, title: '', url: '', model_type: 'url', model_id: null, children: [] }); const addChild = (item) => item.children.push({ client_key: `new-${Date.now()}`, title: '', url: '', model_type: 'url', model_id: null, children: [] }); const removeItem = (list, index) => list.splice(index, 1); const saveItems = () => { itemForm.items = items.value; itemForm.post(route('admin.menus.items', menu.id), { preserveScroll: true }); };
</script>

<template><Head :title="page.meta.title" /><AuthenticatedLayout><AdminPageHeader :title="page.meta.title"><Link :href="route('admin.menus.index')" class="text-sm text-admin-content-muted">Quay lại</Link></AdminPageHeader><div class="mt-6 space-y-6"><AdminErrorSummary :errors="{ ...form.errors, ...itemForm.errors }" /><AdminDataCard title="Thông tin menu"><form class="grid gap-4 sm:grid-cols-2" @submit.prevent="save"><AdminFormField label="Tên menu" for-id="menu-name" :error="form.errors.name"><AdminTextInput id="menu-name" v-model="form.name" /></AdminFormField><AdminFormField label="Vị trí" for-id="menu-location" :error="form.errors.location"><AdminSelect id="menu-location" v-model="form.location" :options="Object.entries(module.locations).map(([key, value]) => ({ key, label: value.label }))" /></AdminFormField><div class="sm:col-span-2"><button type="submit" :disabled="form.processing" class="rounded-lg bg-admin-accent px-5 py-2 text-sm font-semibold text-admin-page">Lưu thông tin</button></div></form></AdminDataCard><AdminDataCard v-if="menu" title="Cấu trúc mục menu"><div class="flex justify-end"><button type="button" class="rounded-lg border border-admin-border px-3 py-2 text-sm text-admin-content" @click="addItem">Thêm mục</button></div><div class="mt-4 space-y-3"><div v-for="(item, index) in items" :key="item.client_key || item.id" class="border border-admin-border p-3"><div class="grid gap-2 md:grid-cols-[1fr_1fr_10rem_auto]"><AdminTextInput v-model="item.title" placeholder="Nhãn mục" /><AdminTextInput v-model="item.url" placeholder="URL nếu là URL tự do" /><AdminSelect v-model="item.model_type" :options="Object.entries(module.targets).map(([key, value]) => ({ key, label: value.label }))" /><button type="button" class="text-admin-danger" @click="removeItem(items, index)">Xóa</button></div><div class="mt-3 flex gap-3"><button type="button" class="text-sm text-admin-accent" @click="addChild(item)">Thêm mục con</button><span v-if="item.id" class="text-xs text-admin-content-muted">ID {{ item.id }} được giữ nguyên</span></div><div v-for="(child, childIndex) in item.children" :key="child.client_key || child.id" class="mt-3 ml-5 grid gap-2 md:grid-cols-[1fr_1fr_auto]"><AdminTextInput v-model="child.title" placeholder="Nhãn mục con" /><AdminTextInput v-model="child.url" placeholder="URL nếu là URL tự do" /><button type="button" class="text-admin-danger" @click="removeItem(item.children, childIndex)">Xóa</button></div></div></div><div class="mt-5 flex justify-end"><button type="button" :disabled="itemForm.processing" class="rounded-lg bg-admin-accent px-5 py-2 text-sm font-semibold text-admin-page" @click="saveItems">Lưu cấu trúc</button></div></AdminDataCard></div></AuthenticatedLayout></template>
